### PR TITLE
Add failing tests

### PR DESCRIPTION
**Pull request by raffaelecarelle**
Hi @ruudk,

I added 2 failing tests for now: 

Take a look. Thanks!

### CODE REVIEW

**Comment by ruudk** [comment]
@raffaelecarelle Thanks. The tests are not failing though 😁

**Comment by raffaelecarelle** [comment]
sorry @ruudk, my fault :cry:. Now their are failing

**Comment by raffaelecarelle** [comment]
I thought a solution for CustomRenderPointTest:

```php
// TwigStan\PHPStan\Collector\ContextFromRenderMethodCallCollector.php

       if (!\in_array($node->name->name, ['render', 'renderView', 'renderStorefront'], true)) {
            return null;
        }

        $varType = $scope->getType($node->var);
        $method = $scope->getMethodReflection($varType, $node->name->toString());

        if ($method === null) {
            return null;
        }

        if (
            !is_a($method->getDeclaringClass()->getName(), AbstractController::class, true)
        ) {
            return null;
        }
```

But I'm not sure on this:

```php
        if (!\in_array($node->name->name, ['render', 'renderView', 'renderStorefront'], true)) {
            return null;
        }
```
It's better something more dynamicall. maybe throughtconfiguration?

**Comment by VincentLanglet** [comment]
Unlike `render` and `renderView` which are methods provided by Symfony/Twig, `renderStoreFront` is a 100% custom function you have in your code base but which is not a generic one everybody will have.

I agree
```
if (!\in_array($node->name->name, ['render', 'renderView', 'renderStorefront'], true)) {
```
is not the right fix because this repo cannot hard-code all the custom method of everybody.

Something about the config might be think, but I feel like it may become complexe, because I could have
```
public function renderStorefront(mixed someArg, string $view, array $parameters = [], ?Response $response = null): Response
    {
        // ...customizations

        return $this->render($view, $parameters, $response);
    }
```
and the order of param is not the same than the original method.

I think for such case the best would be to be able to provide custom Collectors (I dunno if the feature exists already @ruudk). This way you just have to
- Implement `ContextCollector` an interface I'll introduce in https://github.com/twigstan/twigstan/pull/17/files
- Pass it to twigStan

**Comment by raffaelecarelle** [comment]
Custom Collector is the best option for sure! thank you @VincentLanglet :)

**Comment by raffaelecarelle** [comment]
Hello @ruudk, I add a failing test for dynamically global that normally is passed to template when request is defined (so dinamically). We need something can add phpstan annotation as @phpstan-ignore error.identifier (ex. variable.undefined).

**Comment by raffaelecarelle** [comment]
Right. Thank you :)

**Pull request closed without merging**
